stages:
  - build
  - deploy

Build:
  stage: build
  image: docker:25
  services:
    - docker:25-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
Deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - echo "Using kubeconfig at; $KUBECONFIG"
    - kubectl config get-contexts
    - kubectl cluster-info
    - sed -i "s|\${IMAGE_TAG}|$CI_COMMIT_SHORT_SHA|g" Kubernetes/*.yml
    - kubectl apply -f Kubernetes/
    - |
      if ! kubectl rollout status deployment expense-deployment -n expense-app --timeout=120s; then
        echo "---- Rollout failed, rolling back ---- "
        kubectl rollout undo deployment expense-deployment -n expense-app
        exit 1
      fi
  tags:
    - dev 
  when: manual


