apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-deployment
  namespace: expense-app

spec:

  replicas: 2
  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: expense

  template:
    metadata:
      name: expense-app-pod
      labels:
        app: expense

    spec:        
      containers:
        - name: expense-webapp
          image: registry.gitlab.com/vaibhavc54/expenses-tracker-webapp:${IMAGE_TAG} 
          ports:
          - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: expense-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expense-secret
                  key: SPRING_DATASOURCE_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500"
              memory: "512Gi"

      imagePullSecrets:
      - name: gitlab-creds


