apiVersion: v1
kind: Secret
metadata:
  name: expense-secret
  namespace: expense-app
type: Opaque

data:
  SPRING_DATASOURCE_USERNAME: cm9vdAo= 
  SPRING_DATASOURCE_PASSWORD: VGVzdEAxMjMK
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjMK
